window.portfolioWorks = [
  {
    src: 'media/games/block1010/index.html',
    type: 'game',
    title: '方块1010',
    thumbnail: 'media/games/block1010/splash.85cfd.png'
  },
  {
    src: 'media/games/100-floors/index.html',
    type: 'game',
    title: '100层',
    thumbnail: 'media/games/100-floors/splash.png'
  },
  {
    src: 'media/games/catch-dots/index.html',
    type: 'game',
    title: '接球游戏',
    thumbnail: 'media/games/catch-dots/splash.85cfd.png'
  },
  {
    src: 'media/games/animal-puzzle/index.html',
    type: 'game',
    title: '动物拼图',
    thumbnail: 'media/games/animal-puzzle/splash.85cfd.png'
  },
  {
    src: 'media/games/turnleft-turnright/index.html',
    type: 'game',
    title: '左右转弯',
    thumbnail: 'media/games/turnleft-turnright/splash.85cfd.png'
  },
  {
    src: 'media/games/aircraft-war/index.html',
    type: 'game',
    title: '飞机大战',
    thumbnail: 'media/games/aircraft-war/splash.85cfd.png'
  },
  {
    src: 'media/games/mergen-to10/index.html',
    type: 'game',
    title: '合并到 10',
    thumbnail: 'media/games/mergen-to10/splash.85cfd.png'
  },
  {
    src: 'media/games/tetris1010/index.html',
    type: 'game',
    title: '1010 方块小游戏',
    thumbnail: 'media/games/tetris1010/splash.png'
  },
  {
    src: 'media/games/fast-fruit/index.html',
    type: 'game',
    title: '切水果',
    thumbnail: 'media/games/fast-fruit/splash.png'
  },
  {
    src: 'media/games/classic-2048/index.html',
    type: 'game',
    title: '经典 2048',
    thumbnail: 'media/games/classic-2048/splash.85cfd.png'
  },
  {
    src: 'media/games/jump-joy/index.html',
    type: 'game',
    title: '跳一跳',
    thumbnail: 'media/games/jump-joy/splash.03ce1.png'
  },
  {
    src: 'media/games/feeding-birds/index.html',
    type: 'game',
    title: '喂鸟',
    thumbnail: 'media/games/feeding-birds/splash.03ce1.png'
  },
  { src: 'media/gifs/anim-001.gif', type: 'gif', title: 'GIF 001' },
  { src: 'media/gifs/anim-002.gif', type: 'gif', title: 'GIF 002' },
  { src: 'media/gifs/anim-003.gif', type: 'gif', title: 'GIF 003' },
  { src: 'media/gifs/anim-004.gif', type: 'gif', title: 'GIF 004' },
  { src: 'media/gifs/anim-005.gif', type: 'gif', title: 'GIF 005' },
  { src: 'media/gifs/anim-006.gif', type: 'gif', title: 'GIF 006' },
  { src: 'media/gifs/anim-007.gif', type: 'gif', title: 'GIF 007' },
  { src: 'media/gifs/anim-008.gif', type: 'gif', title: 'GIF 008' },
  { src: 'media/gifs/anim-009.gif', type: 'gif', title: 'GIF 009' },
  { src: 'media/gifs/anim-010.gif', type: 'gif', title: 'GIF 010' },
  { src: 'media/gifs/anim-011.gif', type: 'gif', title: 'GIF 011' },
  { src: 'media/gifs/anim-012.gif', type: 'gif', title: 'GIF 012' },
  { src: 'media/gifs/anim-013.gif', type: 'gif', title: 'GIF 013' },
  { src: 'media/gifs/anim-014.gif', type: 'gif', title: 'GIF 014' },
  { src: 'media/gifs/anim-015.gif', type: 'gif', title: 'GIF 015' },
  { src: 'media/gifs/anim-016.gif', type: 'gif', title: 'GIF 016' },
  { src: 'media/gifs/anim-017.gif', type: 'gif', title: 'GIF 017' },
  { src: 'media/gifs/anim-018.gif', type: 'gif', title: 'GIF 018' },
  { src: 'media/gifs/anim-019.gif', type: 'gif', title: 'GIF 019' },
  { src: 'media/gifs/anim-020.gif', type: 'gif', title: 'GIF 020' },
  { src: 'media/gifs/anim-021.gif', type: 'gif', title: 'GIF 021' },
  { src: 'media/gifs/anim-022.gif', type: 'gif', title: 'GIF 022' },
  { src: 'media/gifs/anim-023.gif', type: 'gif', title: 'GIF 023' },
  { src: 'media/gifs/anim-026.gif', type: 'gif', title: 'GIF 024' },
  { src: 'media/gifs/anim-027.gif', type: 'gif', title: 'GIF 025' },
  { src: 'media/gifs/anim-028.gif', type: 'gif', title: 'GIF 026' },
  { src: 'media/gifs/anim-029.gif', type: 'gif', title: 'GIF 027' },
  { src: 'media/gifs/anim-030.gif', type: 'gif', title: 'GIF 028' },
  { src: 'media/gifs/anim-031.gif', type: 'gif', title: 'GIF 029' },
  { src: 'media/gifs/anim-032.gif', type: 'gif', title: 'GIF 030' },
  { src: 'media/gifs/anim-033.gif', type: 'gif', title: 'GIF 031' },
  { src: 'media/gifs/anim-034.gif', type: 'gif', title: 'GIF 032' },
  { src: 'media/gifs/anim-035.gif', type: 'gif', title: 'GIF 033' },
  { src: 'media/gifs/anim-036.gif', type: 'gif', title: 'GIF 034' },
  { src: 'media/gifs/anim-037.gif', type: 'gif', title: 'GIF 035' },
  { src: 'media/gifs/anim-040.gif', type: 'gif', title: 'GIF 036' },
  { src: 'media/gifs/anim-041.gif', type: 'gif', title: 'GIF 037' },
  { src: 'media/gifs/anim-042.gif', type: 'gif', title: 'GIF 038' },
  { src: 'media/gifs/anim-044.gif', type: 'gif', title: 'GIF 039' },
  { src: 'media/gifs/anim-045.gif', type: 'gif', title: 'GIF 040' },
  { src: 'media/gifs/anim-046.gif', type: 'gif', title: 'GIF 041' },
  { src: 'media/gifs/anim-047.gif', type: 'gif', title: 'GIF 042' },
  { src: 'media/gifs/anim-048.gif', type: 'gif', title: 'GIF 043' },
  { src: 'media/gifs/anim-049.gif', type: 'gif', title: 'GIF 044' },
  { src: 'media/gifs/anim-050.gif', type: 'gif', title: 'GIF 045' },
  { src: 'media/gifs/anim-051.gif', type: 'gif', title: 'GIF 046' },
  { src: 'media/gifs/anim-052.gif', type: 'gif', title: 'GIF 047' },
  { src: 'media/gifs/anim-053.gif', type: 'gif', title: 'GIF 048' },
  { src: 'media/gifs/anim-054.gif', type: 'gif', title: 'GIF 049' },
  { src: 'media/gifs/anim-055.gif', type: 'gif', title: 'GIF 050' },
  { src: 'media/gifs/anim-056.gif', type: 'gif', title: 'GIF 051' },
  { src: 'media/gifs/anim-057.gif', type: 'gif', title: 'GIF 052' },
  { src: 'media/gifs/anim-058.gif', type: 'gif', title: 'GIF 053' },
  { src: 'media/gifs/anim-059.gif', type: 'gif', title: 'GIF 054' },
  { src: 'media/gifs/anim-060.gif', type: 'gif', title: 'GIF 055' },
  { src: 'media/gifs/anim-061.gif', type: 'gif', title: 'GIF 056' },
  { src: 'media/gifs/anim-062.gif', type: 'gif', title: 'GIF 057' },
  { src: 'media/gifs/anim-063.gif', type: 'gif', title: 'GIF 058' },
  { src: 'media/gifs/anim-065.gif', type: 'gif', title: 'GIF 059' },
  { src: 'media/gifs/anim-066.gif', type: 'gif', title: 'GIF 060' },
  { src: 'media/gifs/anim-067.gif', type: 'gif', title: 'GIF 061' },
  { src: 'media/gifs/anim-068.gif', type: 'gif', title: 'GIF 062' },
  { src: 'media/gifs/anim-069.gif', type: 'gif', title: 'GIF 063' },
  { src: 'media/gifs/anim-070.gif', type: 'gif', title: 'GIF 064' },
  { src: 'media/gifs/anim-071.gif', type: 'gif', title: 'GIF 065' },
  { src: 'media/gifs/anim-072.gif', type: 'gif', title: 'GIF 066' },
  { src: 'media/gifs/anim-073.gif', type: 'gif', title: 'GIF 067' },
  { src: 'media/gifs/anim-074.gif', type: 'gif', title: 'GIF 068' },
  { src: 'media/gifs/anim-075.gif', type: 'gif', title: 'GIF 069' },
  { src: 'media/gifs/anim-076.gif', type: 'gif', title: 'GIF 070' },
  { src: 'media/gifs/anim-077.gif', type: 'gif', title: 'GIF 071' },
  { src: 'media/gifs/anim-079.gif', type: 'gif', title: 'GIF 072' },
  { src: 'media/gifs/anim-080.gif', type: 'gif', title: 'GIF 073' },
  { src: 'media/gifs/anim-081.gif', type: 'gif', title: 'GIF 074' },
  { src: 'media/gifs/anim-082.gif', type: 'gif', title: 'GIF 075' },
  { src: 'media/gifs/anim-083.gif', type: 'gif', title: 'GIF 076' },
  { src: 'media/gifs/anim-084.gif', type: 'gif', title: 'GIF 077' },
  { src: 'media/gifs/anim-085.gif', type: 'gif', title: 'GIF 078' },
  { src: 'media/gifs/anim-086.gif', type: 'gif', title: 'GIF 079' },
  { src: 'media/gifs/anim-087.gif', type: 'gif', title: 'GIF 080' },
  { src: 'media/gifs/anim-088.gif', type: 'gif', title: 'GIF 081' },
  { src: 'media/gifs/anim-089.gif', type: 'gif', title: 'GIF 082' },
  { src: 'media/gifs/anim-090.gif', type: 'gif', title: 'GIF 083' },
  { src: 'media/gifs/anim-091.gif', type: 'gif', title: 'GIF 084' },
  { src: 'media/gifs/anim-092.gif', type: 'gif', title: 'GIF 085' },
  { src: 'media/gifs/anim-093.gif', type: 'gif', title: 'GIF 086' },
  { src: 'media/gifs/anim-094.gif', type: 'gif', title: 'GIF 087' },
  { src: 'media/gifs/anim-095.gif', type: 'gif', title: 'GIF 088' },
  { src: 'media/gifs/anim-096.gif', type: 'gif', title: 'GIF 089' },
  { src: 'media/gifs/anim-097.gif', type: 'gif', title: 'GIF 090' },
  { src: 'media/gifs/anim-098.gif', type: 'gif', title: 'GIF 091' },
  { src: 'media/gifs/anim-099.gif', type: 'gif', title: 'GIF 092' },
  { src: 'media/gifs/anim-100.gif', type: 'gif', title: 'GIF 093' },
  { src: 'media/gifs/anim-101.gif', type: 'gif', title: 'GIF 094' },
  { src: 'media/gifs/anim-102.gif', type: 'gif', title: 'GIF 095' },
  { src: 'media/gifs/anim-103.gif', type: 'gif', title: 'GIF 096' },
  { src: 'media/gifs/anim-104.gif', type: 'gif', title: 'GIF 097' },
  { src: 'media/gifs/anim-105.gif', type: 'gif', title: 'GIF 098' },
  { src: 'media/gifs/anim-106.gif', type: 'gif', title: 'GIF 099' },
  { src: 'media/gifs/anim-107.gif', type: 'gif', title: 'GIF 100' },
  { src: 'media/gifs/anim-108.gif', type: 'gif', title: 'GIF 101' },
  { src: 'media/images/shot-001.png', type: 'image', title: 'Image 001' },
  { src: 'media/images/shot-002.png', type: 'image', title: 'Image 002' },
  { src: 'media/images/shot-003.jpg', type: 'image', title: 'Image 003' },
  { src: 'media/images/shot-004.png', type: 'image', title: 'Image 004' },
  { src: 'media/images/shot-005.png', type: 'image', title: 'Image 005' },
  { src: 'media/images/shot-006.jpg', type: 'image', title: 'Image 006' },
  { src: 'media/images/shot-007.jpg', type: 'image', title: 'Image 007' },
  { src: 'media/images/shot-008.png', type: 'image', title: 'Image 008' },
  { src: 'media/images/shot-009.png', type: 'image', title: 'Image 009' },
  { src: 'media/images/shot-010.png', type: 'image', title: 'Image 010' },
  { src: 'media/images/shot-011.png', type: 'image', title: 'Image 011' },
  { src: 'media/images/shot-012.png', type: 'image', title: 'Image 012' },
];
